name: third party build

on: workflow_dispatch

jobs:
  ubuntu: &jobs_ubuntu
    runs-on: ubuntu-16.04
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: install dependency
      run: sudo apt -y install git

    - name: build third party
      run: bash third-party/build-third-party.sh
